name: 'Your name here'
description: 'Provide a description here'
author: 'Your name or organization here'
inputs:
  changelog-header:
    description: 'Changelog header used to track changes for new version'
    required: false
    default: ''
  config-file:
    description: 'Path to YAML config'
    required: false
    default: './zowe-deploy.yml'
  npm-credentials:
    description: 'Username and password for NPM publisher (user:pass)'
    required: false
    default: ''
  npm-email:
    description: 'Email for NPM publisher'
    required: false
    default: ''
  publish-github:
    description: 'Specifies whether to publish a release to GitHub'
    required: false
    default: 'false'
  repo-token:
    description: 'Token with push access to GitHub repo'
    required: true
    default: ''
  skip-version:
    description: 'Skip versioning the project before publishing it'
    required: false
    default: 'false'
  vsce-token:
    description: 'Token to publish extension to VS Code marketplace'
    required: false
    default: ''
runs:
  using: 'node12'
  main: 'dist/index.js'
