name: 'Your name here'
description: 'Provide a description here'
author: 'Your name or organization here'
inputs:
  config-file:
    description: 'Path to YAML config'
    required: false
    default: './zowe-deploy.yml'
  deploy:
    description: 'Specifies type of deploy stage that should run'
    required: false
    default: 'none'
  repo-token:
    description: 'Token with push access to GitHub repo'
    required: true
    default: ''
  version:
    description: 'Specifies whether version stage should run'
    required: false
    default: 'true'
runs:
  using: 'node12'
  main: 'dist/index.js'
