name: 'node-versioner'
description: 'GitHub Action to version and publish a Zowe project'
author: 't1m0thyj'
inputs:
  dry-run:
    description: 'Print the list of actions that would be performed'
    required: false
    default: 'false'
  skip-stages:
    description: 'Comma-separated list of stages that should be skipped'
    required: false
    default: ''
# outputs:
runs:
  using: 'node12'
  main: 'dist/index.js'
