name: 'Your name here'
description: 'Provide a description here'
author: 'Your name or organization here'
inputs:
  changelog-header:
    description: 'Changelog header used to track changes for new version'
    required: false
    default: ''
  config-file:
    description: 'Path to YAML config'
    required: false
    default: './node-deploy.yml'
  github-artifacts:
    description: 'Comma-separated list of files to publish in GitHub release'
    required: false
    default: ''
  npm-credentials:
    description: 'Username and password for NPM login (user:pass)'
    required: false
    default: ''
  npm-email:
    description: 'Email address for NPM login'
    required: false
    default: ''
  npm-registry:
    description: 'Registry where NPM package should be published'
    required: false
    default: ''
  repo-token:
    description: 'Token with push access to GitHub repo'
    required: true
    default: ''
  semver-labels:
    description: 'Comma-separated list of semver labels to detect on PRs'
    required: false
    default: 'release-major,release-minor,release-patch'
  update-version:
    description: 'Update package version if semver label detected on PR'
    required: false
    default: 'false'
runs:
  using: 'node12'
  main: 'dist/index.js'
