name: 'node-versioner'
description: 'GitHub Action to version a Node.js project and publish it to GitHub/NPM registry/VS Code Marketplace'
author: 't1m0thyj'
inputs:
  git-committer-name:
    description: 'Username used to commit changes with Git'
    required: false
    default: 'github-actions[bot]'
  git-committer-email:
    description: 'Email used to commit changes with Git'
    required: false
    default: '41898282+github-actions[bot]@users.noreply.github.com'
  github-token:
    description: 'Token used to create release in GitHub repo'
    required: false
    default: '${{ github.token }}'
  npm-token:
    description: 'Token used to publish package to NPM registry'
    required: false
    default: ''
outputs:
  new-version:
    description: 'The new package version if it has changed'
runs:
  using: 'node12'
  main: 'dist/index.js'
