name: Release

on:
  workflow_dispatch:
    inputs:
      package:
        description: Package name to publish (e.g., core)
        required: true
        type: choice
        default: core
        options: [changelog, core, git, github, npm]
      version:
        description: Version number to publish (e.g., 1.0.0)
        required: false
        type: string
      dry-run:
        description: Dry run mode
        required: false
        type: boolean

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        ref: ${{ github.ref }}

    - uses: actions/setup-node@v2
      with:
        node-version: 'lts/*'

    - run: npm install -g npm@~8.5.0

    - run: |
        npm ci
        npm run build

    - uses: ./
      env:
        GIT_COMMITTER_NAME: GitHub Actions
        GIT_COMMITTER_EMAIL: actions@github.com
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_TOKEN: ${{ secrets.ZOWE_ACTIONS_NPM_TOKEN }}
      with:
        config-dir: .github
        dry-run: ${{ github.event.inputs.dry-run }}
        new-version: ${{ github.event.inputs.version }}
        working-dir: packages/${{ github.event.inputs.package }}
