name: Test

on: [push, pull_request]

jobs:
  build-test:
    if: (github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository) && !contains(github.event.head_commit.message, '[ci skip]')
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        node-version: [12.x, 14.x, 16.x]
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - run: |
        npm ci
        npm run all

  smoke-test:
    if: (github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository) && !contains(github.event.head_commit.message, '[ci skip]')
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - run: |
        echo '{"branches": ["invalid-branch"]}' > .releaserc

    - uses: ./
      with:
        dry-run: true
