name: Test

on: [push, pull_request]

jobs:
  build-test:
    if: (github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository) && !contains(github.event.head_commit.message, '[ci skip]')
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        node-version: [14.x, 16.x, 18.x]
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - if: matrix.node-version == '14.x'
      run: npm install -g npm

    - run: npm install
    
    - run: npm run all

  smoke-test:
    if: (github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository) && !contains(github.event.head_commit.message, '[ci skip]')
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - run: |
        echo '{"branches": ["master","next"]}' > .releaserc

    - uses: ./
      with:
        dry-run: true
